### ISSUE TITLE
Huge amount of lag after placing the shelter

### ISSUE THREAD

**Issue by DuckTapeMan** [mwdossantos/squadroninteractive#1]
Placing multiple items, as soon as I placed the shelter a huge amount of lag, for several minutes. Edit: It happened again, but this time with a hatchery and it almost crashed my computer entirely. Might be my specs though.

**Comment by ForeverLona** [comment]
I have not been able to replicate. Specs attached.

[specs.txt](https://github.com/mwdossantos/squadron/files/1526339/specs.txt)
