### ISSUE TITLE
Dino Spasms

### ISSUE THREAD

**Issue by DuckTapeMan** [mwdossantos/squadroninteractive#10]
The dinos will stop and spasm. Sometimes it looks like they are trying to make up their minds on what to do next.

**Comment by ElysePanici** [comment]
+1

I posted a video of this (called Dino spasm and ride up.mp4) on the google drive. https://drive.google.com/drive/folders/1ybPOpRwujcvQ8bX-wc5S4JVE6h0IYM2J

**Comment by ForeverLona** [comment]
+1

Same issue with Baryonyx

**Comment by keawstudio** [comment]
Same problem here. It happens for me in open spaces. If I put them inside an enclosed space with things (decoration), they don't move, or try to move and can't.

Uploaded two videos about it:
https://drive.google.com/open?id=1RcppTFm8KAWphtJPFH7jBJcIWQchzpSG
https://drive.google.com/open?id=1xP1h5a15jBhai4HTe8nATThK_mRXW0A4
