### ISSUE TITLE
1.1 Low Frame Rate/Low End Computer

### ISSUE THREAD

**Issue by LyneeHart** [mwdossantos/squadroninteractive#114]
Due to my low end computer specs I get very low frames. I have good frames at the start menu and in the DNA globe menu.

Screen Resolution: 1280x720 (native screen resolution)
Graphics Quality: Fastest (changing this setting does not seem to work atm as it doesnt affect graphics/frames)
FPS:2-7
Severity: A. The low frame rate makes the game unplayable.

Specs:
[DxDiag Lynee Hart.txt](https://github.com/mwdossantos/squadroninteractive/files/1537527/DxDiag.Lynee.Hart.txt)

Playing at lower resolutions does give me more fps, the lower I go the better. As the game progresses and optimization is more of a priority it may get better. With this 1.1 build I can see a very slight improvement.

**Comment by mwdossantos** [comment]
Should be much better with 1.2 later today as it's a 64bit build
