### ISSUE TITLE
Game causing major computer lag on highish end computer

### ISSUE THREAD

**Issue by Fdiddy** [mwdossantos/squadroninteractive#118]
I opened the game at high settings and even with nothing built ingame my computer sounds like it going to explode and is causing major computer lag. I run a gtx 760 with a intel i5 7500 @3.4 ghz. 8 gb ram

**Comment by JacobSawyer** [comment]
In all fairness by todays standards this is on the lower end of PCs

**Comment by Fdiddy** [comment]
Its the highest end i5 on the market

**Comment by vkDreamInCode** [comment]
Do you have the version 1 or version 1.1 build of meso?
