### ISSUE TITLE
Camera after Dino Controller

### ISSUE THREAD

**Issue by DuckTapeMan** [mwdossantos/squadroninteractive#12]
After using the dino control my camera just faced the ground. WASD worked but zoom kept on forcing me back to the same position.
![mesozoica 12_3_2017 6_46_32 pm](https://user-images.githubusercontent.com/34223342/33535272-2a472c74-d872-11e7-9d91-5dd08f557395.png)

**Comment by vkDreamInCode** [comment]
I need more information, maybe a gameplay video of what you did before this happens ?
