### ISSUE TITLE
Suggestion-Fences

### ISSUE THREAD

**Issue by JacobSawyer** [mwdossantos/squadroninteractive#122]
The amount of fence options in a game like Zoo Tycoon 2 should be present in a 2017 animal Park game. Having things like wood fences and glass fences would give park that much more personality.
![image](https://user-images.githubusercontent.com/34224008/33695915-66aa2450-dac5-11e7-9432-d7b7247d9348.png)

**Comment by mwdossantos** [comment]
Those fences are present but just not linked into the builds.
