### ISSUE TITLE
1.1 Mamenchisaurus issue

### ISSUE THREAD

**Issue by DuckTapeMan** [mwdossantos/squadroninteractive#123]
The picture will reveal this abomination. I had just breed them after building the basic park.

![mesozoica 12_6_2017 9_02_42 pm](https://user-images.githubusercontent.com/34223342/33696714-2b03e428-dac9-11e7-817a-9db055b86cca.png)

![mesozoica 12_6_2017 9_02_56 pm](https://user-images.githubusercontent.com/34223342/33696716-2c47c656-dac9-11e7-91c0-78be4bab5aa2.png)

![mesozoica 12_6_2017 9_03_08 pm](https://user-images.githubusercontent.com/34223342/33696717-2e1d5748-dac9-11e7-911d-58cf76294844.png)

**Comment by TheAssassinsDen** [comment]
omg they're amazing.

**Comment by mwdossantos** [comment]
What settings are you playing at?
