### ISSUE TITLE
Save Crash

### ISSUE THREAD

**Issue by TheAssassinsDen** [mwdossantos/squadroninteractive#133]
Tried to save my game and it crashed. Didn't have any dinosaurs in the park.

**Comment by vkDreamInCode** [comment]
Does this happen everytime you save or randomly?

**Comment by aPalmer2** [comment]
Same save crash. Everytime.
[error.log](https://github.com/mwdossantos/squadroninteractive/files/1538598/error.log)
[output_log.txt](https://github.com/mwdossantos/squadroninteractive/files/1538599/output_log.txt)
