### ISSUE TITLE
Crash Report 1.1 1

### ISSUE THREAD

**Issue by JacobSawyer** [mwdossantos/squadroninteractive#134]
happened when I tried to save. Happened twice in 1.0, first time in 1.1
[2017-12-06_215822.zip](https://github.com/mwdossantos/squadroninteractive/files/1537824/2017-12-06_215822.zip)

**Comment by vkDreamInCode** [comment]
Does this happen everytime you save or randomly?

**Comment by JacobSawyer** [comment]
It happens randomly but more often than saving works
