### ISSUE TITLE
Suggestion-UI

### ISSUE THREAD

**Issue by JacobSawyer** [mwdossantos/squadroninteractive#136]
Its hard to type in words what i expect from the menu but I will try. 
first thing is I think it is overall to small. Often you cant see a wide selection on it and it can be annoying to always have to scroll to find what you are looking for. 
It NEEDS to be separated into sections better, Have a menu for decorations, have a menu for signs, have a menu for lights, have a menu for fences, have a menu for paths (and have different colors to choose from off the bat, have a light brown path, a dark brown path, asphalt, etc. It takes to much time for the casual player who isnt that good at creating things to use and takes to much time to figure out.) Look at games like zoo tycoon, JPOG, and even prehistoric kingdoms demo to find a good use of the menus in UI. 
Need more on the screen. I get what your trying to go for but I think it needs something more so where you would have number of visitors and dinos somewhere in the top left, amount of money in the top right, and then the items menu in the bottom left. Tycoon gamers like to see these stats displayed on their screens because it makes the game have a more organized feel. 
The Hatchery UI in itself needs work. When you click on the hatchery only 2 things should appear. Open hatchery and Edit. That goes for everything really. When you click on something it should have 2 options (3 for hatchery I guess.) Edit and destroy. All these other things popping up right away feels very clunky. 
I suggest going back to your tech demo menu system if you are not wanting to do a complete rework, or look at a game like zoo tycoon 2 and try and mirror it as much as you can. 

If this was to improve it would make the game feel leagues better.

**Comment by mwdossantos** [comment]
You can resize the toolbar with the handles in each corner. Will take a look at the other suggestions!
