### ISSUE TITLE
1.1 still DNA problems wessex formation

### ISSUE THREAD

**Issue by aPalmer2** [mwdossantos/squadroninteractive#138]
When you select black market in wessex formation if you click uncommon you are guaranteed two skins. you can replicate this every time with a new save. The poor option will never give you anything, even after 50+ tries.

**Comment by mwdossantos** [comment]
That's because that formation doesn't have any "poor" skins. The uncommon skins are garuanteed because the chance to get nothing is almost 0%. When money influence is added into the game it will be fine.
