### ISSUE TITLE
Suggestion: Placing Hatcheries

### ISSUE THREAD

**Issue by TheAssassinsDen** [mwdossantos/squadroninteractive#148]
When placing hatcheries, if you place a few all at once, and select them, they are are treated as one hatchery. There should maybe be a way to separate a model from a modular piece.  Right now, if you want multiple hatcheries, you have to place a hatchery, then exit modular set, then create new modular set, and place another.

**Comment by ForeverLona** [comment]
+1 game will improve dramatically with a change like this
