### ISSUE TITLE
Saving/Loading

### ISSUE THREAD

**Issue by ElysePanici** [mwdossantos/squadroninteractive#15]
There's a problem with the save and/or load system. I save a park, exit the game, and when I load it back up my Dinos are all babies + the dinos seem to be locked again at the hatchery.  This has happened every single time...10 times so far. 

Computer specs:

Processor: Intel(R) Xeon(R) CPU X5470 @ 3.33GHz
 
Video Card: NVIDIA GeForce GTX 1060 6GB (latest drivers)
 
RAM: 8.0 GB
 
Operating System: Microsoft Windows 7 Ultimate Edition Service Pack 1 (build 7601), 64-bit

EDIT: On the 11th try, my game crashed while saving, resulting in the same outcome as above.

Files attached below from the crash. 

Video: https://drive.google.com/open?id=1FRKChXt5hhvzjCb7zPwODBuI6oYBudmW

[error.log](https://github.com/mwdossantos/squadron/files/1525657/error.log)
[output_log.txt](https://github.com/mwdossantos/squadron/files/1525658/output_log.txt)

**Comment by vkDreamInCode** [comment]
Yes im soo stupid, completly forgot to save the unlocking data
