### ISSUE TITLE
Lag Report: No Pieces or Plants, 40 Dinos

### ISSUE THREAD

**Issue by TheAssassinsDen** [mwdossantos/squadroninteractive#152]
Graphics Setting: Fantastic
PC specs: 8GB ram
                i5 4590 Processor
                Rx 480 graphics card

 I have a park with just dinos and hatcheries in it. 40 dinos are currently in game, and I'm getting almost no lag, but still getting a small lag spike every few seconds which makes it a bit hard to control the camera. 

UPDATE
I exited the game and then opened the game and went back into the empty park with hatcheries and 40 dinos, and found a tremendous amount of lag, pretty much to the point where it was unplayable. The Dev Console wouldn't close either. 
![bug 11](https://user-images.githubusercontent.com/30283568/33737783-3220adc6-db4c-11e7-9c0e-6a847d55c9bd.png)
![bug 12](https://user-images.githubusercontent.com/30283568/33738272-9a6a77a8-db4d-11e7-9cb0-340014215c26.png)

 UPDATE 2
I tried opening the park on Fastest graphics, and it still hardcore lagged.

**Comment by vkDreamInCode** [comment]
The lag is cause of the logs, can you send me the log file?
