### ISSUE TITLE
Cannot Exit Game

### ISSUE THREAD

**Issue by TheAssassinsDen** [mwdossantos/squadroninteractive#153]
I can't exit the game, and the Dev Console appears when I try.
![bug 9](https://user-images.githubusercontent.com/30283568/33737591-8f7b2722-db4b-11e7-9c03-a5bac665fc73.png)
![bug 12](https://user-images.githubusercontent.com/30283568/33737888-7b8a6808-db4c-11e7-8250-317f9805d097.png)

**Comment by vkDreamInCode** [comment]
Can you send me the log file?
