### ISSUE TITLE
Mamenchisaurus 

### ISSUE THREAD

**Issue by TheAssassinsDen** [mwdossantos/squadroninteractive#158]
Mamenchisaurus looks very weird on Fastest graphics setting. It has huge seams (even when zoomed in), it's face is basically gone, it's legs look like rectangular columns.  
![bug 18](https://user-images.githubusercontent.com/30283568/33740858-1349ae4c-db57-11e7-84a5-3d21ae0ee01b.png)

UPDATE
Hatchery door closes before Mamen walks out of the hatchery. it clips right through. The dino then just stands out side the hatchery and doesn't go anywhere, though you can fix this by controlling the animal then letting it walk freely. It's idle animation also has an odd stutter. 

UPDATE

Mamen seems to only walk on a grid, left, right, back, forward. They wont walk diagonally.

**Comment by mwdossantos** [comment]
This is because on the fastest graphic setting it only shows the last LOD at all times.
