### ISSUE TITLE
Dinosaur Stacking

### ISSUE THREAD

**Issue by TheAssassinsDen** [mwdossantos/squadroninteractive#162]
Dinosaurs still like to stack on top of each other, dino spread value needs to go bigger
![bug 19](https://user-images.githubusercontent.com/30283568/33742285-7bba7fa6-db5c-11e7-9193-c11ff6adaeb9.png)

**Comment by vordik660** [comment]
i have a bunch of vids about this and ill upload all of them because there seems to be a AI issue because they stand around for ages doing nothing until they want to go to sleep.
