### ISSUE TITLE
Suggestion: Rotating Grid

### ISSUE THREAD

**Issue by DuckTapeMan** [mwdossantos/squadroninteractive#17]
When rotating an object it would be nice to have a grid where we can snap to a certain position.

**Comment by TheAssassinsDen** [comment]
when placing an object, click on 'free movement' and it'll change to grid snapping objects

**Comment by TheNickinger** [comment]
+1

Besides the fact that the alignment / placing grid needs some "love" in general (like already discussed in other posts) it would be nice, if there was a (optional) visualisation of the grid while placing objects and building.
