### ISSUE TITLE
1.2 Unable to do anything after creating a few dinos in the hatchery

### ISSUE THREAD

**Issue by DuckTapeMan** [mwdossantos/squadroninteractive#183]
I just started up the game, placed a hatchery and created 6 dinos. After I got more from the DNA, I couldn't select anything on the toolbar. I also had this issue on 1.1

https://drive.google.com/file/d/12StPcAlPmQ0DRUbAqn1Fqzn9GdvzTbUV/view

**Comment by vkDreamInCode** [comment]
yeah this is one of the last game breaking bugs, try to find a pattern

**Comment by vkDreamInCode** [comment]
and i cant open the drive link, dont have permission
