### ISSUE TITLE
1.2 - Bug - "Loading Error"

### ISSUE THREAD

**Issue by ForeverLona** [mwdossantos/squadroninteractive#185]
Loading error pops up in developers log when starting new park. Error log attached. 
[output_log.txt](https://github.com/mwdossantos/squadroninteractive/files/1542027/output_log.txt)
[specs.txt](https://github.com/mwdossantos/squadroninteractive/files/1542028/specs.txt)

**Comment by vkDreamInCode** [comment]
Did the game crash?

**Comment by ForeverLona** [comment]
Not initially no. It did develop the "can't open hatchery cog" bug
