### ISSUE TITLE
Dino controller issues

### ISSUE THREAD

**Issue by DuckTapeMan** [mwdossantos/squadroninteractive#2]
Clicked on the dino controller, wouldn't let me move the dino or exit the controller mode. Has happened twice and had to force close the game. Also, the dinos were still so I was trying to move them.
Sorry, these are poor quality and have background sound but its the best I can do.

Short Version: https://drive.google.com/file/d/1o4ii5-andXk3-XHSld7dSv8Z5eXJhd_I/view

Long Version: https://drive.google.com/file/d/1BefxTmcwocdCYlJl-PZsO-7X7giUYYoG/view

**Comment by vkDreamInCode** [comment]
haha wow you have so much lag
