### ISSUE TITLE
Dinosaurs Dont spawn and break Hatchery

### ISSUE THREAD

**Issue by JacobSawyer** [mwdossantos/squadroninteractive#20]
When I try and make the saurapod the door to the hatchery opens and its stuck at 99% and doesnt ever spawn, sat there for 5 minutes. 
![image](https://user-images.githubusercontent.com/34224008/33536659-05116424-d87c-11e7-970f-21717c253cad.png)

**Comment by ElysePanici** [comment]
+ 1, I've gotten this too

**Comment by vkDreamInCode** [comment]
What dinosaur did you try to spawn?

**Comment by keawstudio** [comment]
Happened to me too, but not with all dinos. After two Hatchery stopped to work, saying that the dinos are 99%, or no dino at all, I created another two Hatcherys and breed other dinos. Those worked, but the dinos was breed too fast, like, in seconds. The first ones I created took some time.

**Comment by NathanaelHembree** [comment]
I have this as well, the Dino is the Sauropod from the Chinese dig site that doesn't have the Velociraptor. I forgot both of their names.

**Comment by keawstudio** [comment]
For me happened with the mamenchi-something. The other dinos hatched too quickly. Only the raptors worked.

Showed in the video of issue #86 at 01:12, 01:37, 03:03, 09:38
