### ISSUE TITLE
Re-loading resets day/night cycle-1.3

### ISSUE THREAD

**Issue by Warcodered** [mwdossantos/squadroninteractive#206]
Build: 1.3

Actual Result: I saved the game when it was dark when the sun had set in the game. I exited out of the game and reloaded it and it was the middle of the day bright out like when I started the game.

Expected Result: I expected that since I saved at night when I reloaded it would be night.

Steps to Replicate: Start the game and once the reaches night save and reload.

Severity: D It doesn't stop the game from working and is mostly cosmetic.

Specs: 

Computer Information:
    Manufacturer:  MSI
    Model:  MS-7522
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7 CPU         960  @ 3.20GHz
    CPU Family:  0x6
    CPU Model:  0x1a
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  3208 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce GTX 960
    DirectX Driver Name:  nvldumd.dll
    Driver Version:  23.21.13.8813
    DirectX Driver Version:  23.21.13.8813
    Driver Date: 10 27 2017
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 74 Hz
    DirectX Card: NVIDIA GeForce GTX 960
    VendorID:  0x10de
    DeviceID:  0x1401
    Revision:  0xa1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 16.06" x 10.04" (18.94" diag)
                                            40.8cm x 25.5cm (48.1cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2047 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Speakers (Realtek High Definiti

Memory:
    RAM:  12279 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  DVD
    Total Hard Disk Space Available:  2097048 Mb
    Largest Free Hard Disk Block:  377728 Mb
    OS Install Date: Dec 31 1969
    Game Controller: None detected
    VR Headset: None detected

**Comment by JacobSawyer** [comment]
This is how I get out of the drdark nights so I can actually see
