### ISSUE TITLE
1.3 suggestion one unit fences

### ISSUE THREAD

**Issue by JamesBear99** [mwdossantos/squadroninteractive#227]
I think if the fences were able to be placed in units of one like paths players could have way more control over there park, and how it is layed out. Currently with the fences being placed as two gives the player far less control, and it leads to ugly uneven layouts like this.
![mesozoica 12_9_2017 12_50_20 pm](https://user-images.githubusercontent.com/11201908/33799011-814a8c6a-dce0-11e7-82a4-476b84f8b117.png)

**Comment by ForeverLona** [comment]
+1
