### ISSUE TITLE
1.3 crash in a certain angle

### ISSUE THREAD

**Issue by switchkeys** [mwdossantos/squadroninteractive#244]
everytime i get in a certain low angle(close to the ground) the game crashes, to much my entire computer freezes

**Comment by vkDreamInCode** [comment]
how you mean low angle? with the camera or?

**Comment by switchkeys** [comment]
with the camera yes, when i control the camera with the mouse and go near the ground (as if you are a visitor) the game just suddenly has a massive fps drop and a few seconds later everything freezes and i have to turn off the computer manually to get the pc working again

**Comment by vkDreamInCode** [comment]
and is there anything placed on the ground or?

**Comment by switchkeys** [comment]
the first time it happend i moved a baryonx to a swamp area i made, 2nd time was close to a fence
