### ISSUE TITLE
1.3 suggestion for sensitivity in placement 

### ISSUE THREAD

**Issue by casmorrison** [mwdossantos/squadroninteractive#247]
So I made a complex hatchery with some of the rocks goin below ground with plants etc. 
When I saved it and placed as a modular set (saved) I couldn't have the floor of the hatchery on the ground- moving it resulted in it either going below or above ?

I think the movement needs to be more sensitive when placing buildings as they need to go on the ground

Dinos built from such hatcheries wouldn't move of their own accord  And were in mid air

**Comment by casmorrison** [comment]
Ie. To have small increments in moving on the x y and z axis

**Comment by mwdossantos** [comment]
Press and hold shift when placing, it will allow you to precicisely align it to the ground
