### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by JacobSawyer** [mwdossantos/squadroninteractive#253]
UI change didn't do anything other than visually change the icons. All the same issues are there. Its just very unorganized. Tycoon games should ALWAYS display things like visitors, money, dinosaurs. on the screen and it should be separate from the menu's. Go back to tech demo style of menu. Its organized and looks like a game. This was just very disappointing after being told that you were fixing it in the .4 update. The build selection needs to be in categories (fences, walls, roofs, decorations, lights etc. The hatchery needs the menu to be changed to where you click on it and you immediately see create dino. Look at literally any other tycoon game and they will show how the UI should be like.

**Comment by ElysePanici** [comment]
+1 to this
