### ISSUE TITLE
Mesozoica 1.5 Hatchery Menu Problem

### ISSUE THREAD

**Issue by metternich1815** [mwdossantos/squadroninteractive#278]
Just as in 1.4, the hatchery menu does not allow me to scroll over from the Allosaurus.

**Comment by vkDreamInCode** [comment]
can you make a video?

**Comment by metternich1815** [comment]
This was a video I made in 1.4, but it does the same thing: https://drive.google.com/open?id=1-zagGIAfw9aEh9UbZhkPp6LfVd9I6_-R

**Comment by metternich1815** [comment]
Never mind on this one, apparently it was just me not knowing how to work it.  Lol.
