### ISSUE TITLE
1.5 WE NEED FEEDERS!!!!

### ISSUE THREAD

**Issue by TheHarvNut** [mwdossantos/squadroninteractive#292]
Water troughs, and Herbo and Carno feeders boi!

http://4.bp.blogspot.com/-uxuSddivZbI/US9T-uPe7mI/AAAAAAAAAQU/dt6eui99zu8/s1600/Water+Trough+1.jpg

Same for meat and veg!

**Comment by ElysePanici** [comment]
+1, Twitch chat really wants them (autofeeders) too
