### ISSUE TITLE
1.6 - sliding visitors 

### ISSUE THREAD

**Issue by casmorrison** [mwdossantos/squadroninteractive#304]
I had visitors with no animation or sliding in the following scenario : 

Visitors slide on path if there are no fences - May be  a density thing, didn't have a huge amount of path 

1)Built dinos first
2)Then entrance 
3)Then path

**Comment by JonestheMoblin** [comment]
I got the same thing right after hatching a Velociraptor.

Built Entrance
Built Paths
Built Hatcheries
Hatched Raptor

https://drive.google.com/file/d/1oWW9eLCafhPEbw0dQKeRzF79vY02bMZl/view?usp=sharing
