### ISSUE TITLE
James Bear crash 01

### ISSUE THREAD

**Issue by JamesBear99** [mwdossantos/squadroninteractive#32]
I was attempting to save my game. I the save screen did not pop up, after several attempts it came up then closed. Then the do you want to overwrite your previous data message came up and the game crashed.

[error.log](https://github.com/mwdossantos/squadron/files/1525845/error.log)
[output_log.txt](https://github.com/mwdossantos/squadron/files/1525846/output_log.txt)

**Comment by vkDreamInCode** [comment]
Did it worked before? The game saving?

**Comment by JamesBear99** [comment]
yes I was able to load games. Another thing when I loaded up that save game my dinosaurs would start back as young animals with a different skin and would not do anything, Then when I attempted to take control of them they would just be idle and I would be unable to do anything except move around the camera. unable to exit out of dinosaur control mode. I had to end the game using task manager. I was able to replicate this bug by loading up that save game.
