### ISSUE TITLE
1.7 Allosaur has zero animations and just slides around like a statue.

### ISSUE THREAD

**Issue by Larvtrams** [mwdossantos/squadroninteractive#324]
Instead of walking or doing anything it slides around like a statue.
both when controlled and on its own. no other animations seem to work either.

https://drive.google.com/open?id=18phg2yng2DOjMOJn4NYCkoopfNoDe0PR

Fullscreen 1440p 144hz
Gquality "Fantastic"

4790k@4.5ghz
32gb ddr3
1080ti
m.2 ssd

**Comment by ForeverLona** [comment]
+1
