### ISSUE TITLE
1.7 "Kill Dinosaur" - Command not working.

### ISSUE THREAD

**Issue by Larvtrams** [mwdossantos/squadroninteractive#327]
My dinosaurs suck and do nothing, (Separate issue) but when i try to punish them by klicking "Kill dinosaur" nothing at all happens, they just smile and keep doing absolutely nothing, instead of dying.

https://drive.google.com/open?id=1RXXKi_lkmf57-AeIdwxpKB2iP0oVP0a6

Fullscreen 1440p 144hz
Gquality "Fantastic"

4790k@4.5ghz
32gb ddr3
1080ti
m.2 ssd

**Comment by ForeverLona** [comment]
+1
