### ISSUE TITLE
All Dino AI Overall Report

### ISSUE THREAD

**Issue by TheAssassinsDen** [mwdossantos/squadroninteractive#349]
For this Issue, I have made separate pens for all dinos and put 1-5 dinos in each pen. All have the same plants and rocks and one hatchery. 

-----------------------------------------------------------------------------------------------------------

Albertosaurus: all the Albertos in my park are just walking in one direction. I can control and move them but when I go out of controlling, they start walking that one way again, into the fence. 
![bug 30](https://user-images.githubusercontent.com/30283568/34402146-c55c49fc-eb54-11e7-997b-919831339d0d.png)

-----------------------------------------------------------------------------------------------------------

Velociraptor: Velo don't move from hatchery. I can control them, but otherwise they stay in the hatchery and don't move around.
EDIT: Velos in the hatchery that I didn't move out have now vanished, after the hatchery door closed. 

-----------------------------------------------------------------------------------------------------------

Argentinosaurus: Argent is doing the same as Alberto, walking in one direction (same direction as Alberto, and its effecting all Argents in my park)
![bug 31](https://user-images.githubusercontent.com/30283568/34402318-90fe9b32-eb55-11e7-8f5c-fda6883b3a6c.png)

-----------------------------------------------------------------------------------------------------------

Allosaurus: Allo has no animations whatsoever. I can control it and it glides around. It does have sound affects when using the mouse buttons. It doesn't move around, sits frozen in one spot when not controlled.

-----------------------------------------------------------------------------------------------------------

Tarbosaurus: Tarbo has the exact same problem as Alberto and Argent concerning moving in one direction. It effects all Tarbos in my park. 

-----------------------------------------------------------------------------------------------------------

Stegosaurus: Stego appears to be stuck in the hatchery door, and shaking slightly, as if its trying to play an animation but gets interrupted.
![bug 33](https://user-images.githubusercontent.com/30283568/34402511-da5124a2-eb56-11e7-9137-20b5cc61c62c.png)
EDIT: I took control of the Stego and easily unstuck it from the hatchery door, and the door closed. Once I left its control, it began walking around its enclosure and acting like an animal would.

-----------------------------------------------------------------------------------------------------------

Baryonyx: Bary is not moving around its enclosure. I can control and move it, but otherwise it just stays idle in its enclosure, though it has decided to lay down. 
![bug 34](https://user-images.githubusercontent.com/30283568/34402668-fc56ee50-eb57-11e7-852e-449296c23e49.png

-----------------------------------------------------------------------------------------------------------

Parasaurolophus: 3 Paras in an enclosure seem to be stuck. 
Video > https://drive.google.com/open?id=1iCU6TiuI_WjRty7C3OaQWuWq5qVDPWu9
EDIT: I took control of them 1 by one and moved them away from the hatchery, one called out,a nd one by one, they ran back to the exact same spot as seen in the video. 

-----------------------------------------------------------------------------------------------------------

Anatosaurus: I bought 3 Anatos and as they spawned, the hatchery door opened, they didn't move out of the hatchery, and when the door closed, they disappeared. This happened one by one.
Video > https://drive.google.com/open?id=1J8gORXeA2I0XT4B6-aWOGcIayV_N4qrX

-----------------------------------------------------------------------------------------------------------

Mamenchisaurus: AI seems to be working fine. walking around, eating, etc. Everything seems fine.

-----------------------------------------------------------------------------------------------------------

Pachyrhinosaurus: AI seems to be working fine. walking around, eating, etc. Everything seems fine.
EDIT: A Pachy is now walking into a rock and not going around it.

**Comment by vkDreamInCode** [comment]
Did you at any point before the bugs happend control the dinosaur?

**Comment by TheAssassinsDen** [comment]
No, I controlled the dinos only after I saw them bugging out.
