### ISSUE TITLE
Unable to Exit Path Placement Screen

### ISSUE THREAD

**Issue by ForeverLona** [mwdossantos/squadroninteractive#35]
After placing a set of fences and pathways, the user is unable to exit the Path/Fence Placement screen

Video shows steps taken - this has happened each time I have taken these actions (place path, place fence, delete path, place path)

Video attached - https://drive.google.com/open?id=1-1UGHdS8Lr--P4bzMV5-EWLLeLs4JOPf

[specs.txt](https://github.com/mwdossantos/squadron/files/1525895/specs.txt)

**Comment by vkDreamInCode** [comment]
i cant seem to replicate this bug on my end, if it happends again video it :)

**Comment by ForeverLona** [comment]
There is a video link in the OP - I have replicated this several times now. I can get another video if you like?
