### ISSUE TITLE
UI Control Suggestions

### ISSUE THREAD

**Issue by Dracovitch** [mwdossantos/squadroninteractive#365]
Two things I think could improve the user control of the UI. 

1. Hitting the escape button should take you back to the previous screen/menu. Several times have I hit esc only to realize I have to manually click buttons. Shortcut keys are tech. 

2. Dino UI bar should be a fixed point on the screen and NOT move with them. It can get mildly infuriating at times trying to click the control dino button and miss because they moved just slightly out of range.

**Comment by ForeverLona** [comment]
+1 to both of these
