### ISSUE TITLE
1.8 Mamemch- parts of tree serpent skin is missing on the model 

### ISSUE THREAD

**Issue by casmorrison** [mwdossantos/squadroninteractive#366]
![mamenchi missing skin 2](https://user-images.githubusercontent.com/34281278/34462980-020180bc-ee47-11e7-852e-199c743cb4da.jpg)
![mamenchi missing skin](https://user-images.githubusercontent.com/34281278/34462981-0224a1aa-ee47-11e7-9230-aa92ae530155.jpg)

Both when you dig it up on the world map and in game after building it . parts of the tree serpent skin is missing

Please see the images above

no other skin have i come across has experienced this problem

**Comment by nqwebasaurus** [comment]
It also appears in the "traveler" skin
