### ISSUE TITLE
1.8.1 - Sound - Animals make no sounds unless fighting

### ISSUE THREAD

**Issue by ForeverLona** [mwdossantos/squadroninteractive#399]
I would expect some ambient roars, grunts, eating, drinking or snuffling noises. Currently the dinosaurs are too quiet

Linked to #359

**Comment by nqwebasaurus** [comment]
I agree that there should be more sound coming from the animals such as walking and stomping, drinking and eating sounds; however I feel that vocalizations should still be uncommon as large animals normally remain quiet the most of the time.
