### ISSUE TITLE
Suggestion - Split Object Placement and Modular Build

### ISSUE THREAD

**Issue by ForeverLona** [mwdossantos/squadroninteractive#40]
I am finding it very counter intuitive when placing objects using the modular tool. I would like to place multiple (but not linked) objects at once - for example, fences, paths around the fence, hatchery and foliage. Currently if you do all this at once in the modular tool they will then be placed as a single editable item. I would expect each item to be individually editable and movable. Splitting out a "Object Placement" screen from the Modular build would allow for both bulk single item placement and the current modular placement.

**Comment by ElysePanici** [comment]
+1 to this

**Comment by ForeverLona** [comment]
No longer an issue
