### ISSUE TITLE
1.81- Dinos ai walking continusly into a single tree and clumping together 

### ISSUE THREAD

**Issue by casmorrison** [mwdossantos/squadroninteractive#401]
2 videos 

https://drive.google.com/file/d/15d7pd0sOV9qKcD0jy4OPO1BmAYeuP707/view?usp=sharing

https://drive.google.com/file/d/1h86MjIDPQX65-AJT8S-5ZEPy28BIg_eE/view?usp=sharing

Set uploaded here and the tag below the link can help find the file on the page 
https://discordapp.com/channels/386963103381716993/387372537866354709
1.81 tree clumping bug

Bug description
I built up 85 dinosaurs and there were very few issues or clumping

Then, I built a modular set of bald cypress ( and have uploaded it). The trees were very sparse and there was plenty of space to walking between the trees. Once the trees were placed, the dinos were stuck walking between the two trees or three trees which were for decorations.  rather than walking around the tree (which would be expected) but just walks forward and refuses to change path. The dinos continue to walk forward, then more dinos get stuck and they start to swarm clump

The issue maybe due to the fact its (the trees) are a blueprint and it acts differently than a singular tree (or a group of trees placed individually  forming a clump or a forest). The blueprint may act like a large building control zone so the dinos cant walk through them nor can figure out how to walk around it especially if they form a large forest) . If so, maybe there needs to be a warming about making modular forests - not to do it 

Also a single tree stopped a stego and another stopped another edmonto, there is another a video, but internet is too slow though

**Comment by vkDreamInCode** [comment]
Does it happen to only thag specific tree?

**Comment by casmorrison** [comment]
https://drive.google.com/file/d/1GV-jnXYcvILrxbr5JeGK6U_oxwLVJcgJ/view?usp=sharing

No happens with other trees as well, if they are close together. The dinos dont walk around but just go forward

**Comment by casmorrison** [comment]
that too was a blueprint though
