### ISSUE TITLE
Crash - Complete Lockdown of Computer

### ISSUE THREAD

**Issue by ForeverLona** [mwdossantos/squadroninteractive#41]
I dont have much to go on with this, but I just experienced a lock down crash that required a full computer restart. 

All I have is that I had 2 Baryonyx, and it occurred after moving a large modular set that included the paths and fence surrounding the paddock.
[specs.txt](https://github.com/mwdossantos/squadron/files/1526189/specs.txt)

**Comment by JacobSawyer** [comment]
I have reported the same thing that occurred 3 separate times having to do with moving a placing paths while fences and bary were present.

**Comment by vkDreamInCode** [comment]
How large were the modular sets?

**Comment by ForeverLona** [comment]
This video shows an approximate size - https://drive.google.com/open?id=1-1UGHdS8Lr--P4bzMV5-EWLLeLs4JOPf

I had also added 2 Baryonyx, a Hatchery, and a small amount of foliage. The foliage was a separate module and so was not included in the moving of the fences and path set.

**Comment by vkDreamInCode** [comment]
Did you get a crash report?

**Comment by ForeverLona** [comment]
Unfortunately not - my only recourse was a hard reset of the PC
