### ISSUE TITLE
1.8.1 Pressing ESC does nothing

### ISSUE THREAD

**Issue by Andrej22111** [mwdossantos/squadroninteractive#413]
Pressing the ESCAPE key or trying to control dinosaur or anything doesen't work untill you close off build UI to it's "Home" screen, then you can click on stuff and esc back to main menu.

**Comment by TheNickinger** [comment]
For me, in sandbox mode ("normal park mode" not tested yet), the ESC key sometimes is functionless, so I can not save or leave the game correctly.
This also happens if the build mode is completely closed or was not opened in the session.
