### ISSUE TITLE
Mesozoica FPS Problems

### ISSUE THREAD

**Issue by WolfGankK** [mwdossantos/squadroninteractive#419]
When I start the game everything is ok. In Menu/Settings i have a 300 Fps, at loading too...
But When game is loaded and i can see world my 60-100 fps go to 3-4 WTF??? When my camera go to Inside a Hatchery i have a good fps again... in World Map is good 60 fps... BUT I CANT BUILD A PARK OR SOMETHING... Plz repair it... 
Planet Coaster And Mesozoica have a same Graphic requirements. 
And Plancet Coaster Work on my comp very smooth and good...
Well why meso is not work smooth?

**Comment by vkDreamInCode** [comment]
do you have a constant fps drop? or is it when you place objects?

**Comment by Loganunicorn** [comment]
I believe its the grass that is causing the fps drop, we should have a grass disable option
