### ISSUE TITLE
Dinosaurs Stuck

### ISSUE THREAD

**Issue by AnnaGoesLaLa** [mwdossantos/squadroninteractive#424]
Noticed that all Dinos like to get stuck by their self after some time if wandering around. They like to get stuck on a bush, a tree, the fence, the water pond, the feeding station (hay and the flesh-thingy) or like a big pile into each other. Also the AL and UI is horrible. Please fix that herbs start attacking other herbs immediately on sight.

**Comment by unicorncatbug** [comment]
Yeah, I have to control them to just get them unstuck, it does get quite annoying
