### ISSUE TITLE
Suggestion-DNA and Fossil finding system

### ISSUE THREAD

**Issue by nqwebasaurus** [mwdossantos/squadroninteractive#429]
This game shows much promise and I like it as it's turning out, however the Fossil finding leaves me a bit underwhelmed.
May be it's just me that I always imagined it to be somewhat similiar to the DNA system in Jurassic Park Operation Genesis, but as it stands now I feel it's to quick and it doesn't leave me with any sense of accomplishment by finding a new dinosaur (especially seen as you can buy from the black market and get them instantly).
I would personally suggest a similiar approach as in Jurassic Park Operation Genesis where to unlock a dinosaur you had to extract DNA from various fossils of the same species accumulating a high enough percentage to clone it.
This way it takes more time to get everything and makes the player work for the dinosaur they really want.
May be make the skins special unlocks that you "win" at certain DNA milestones (i.e. At 50% DNA completion you get a skin for said animal).
The black market would become more similiar to the fossil market in JPOG serving as a way to easily obtain fossils of certain species so that it can make the game faster for the ones who do not wish to invest the time in the digging but still not making it so that you can instantly obtain everything.
Also i would implement a way to skip the cutscene where you open up the box to see what you've found, sometimes it gets a bit annoying having to sit through it every time.
This way I think it would partially resolve the issue that players are having right now that the game feels barebones; while the game still has a long way to go and most things are yet to be added, at least in order to see and unlock everything there is right now in the game it takes a while and people don't get bored too quickly since they have a bit of work to do before finishing everything up and, if the update come quick enough may be you could add things fast enough that people don't have the time to finish researching everything by the time new things get added :)

**Comment by unicorncatbug** [comment]
I agree, it is so easy to get dinosaurs, I literally started a new game at 10:00 am today, it’s 12:00 rn, I already have every dinosaur bc it’s so simple to get them, we need it to be harder, the fossil finding is a very good idea

**Comment by RoseCollie** [comment]
I am actually annoyed by how long the current fossil system takes, especially since I can't buy multiple dig teams to do more than one site at a time. The sequence of opening the "loot" boxes should be shortened by half.

**Comment by nqwebasaurus** [comment]
What I'm proposing is not to make more time consuming the animation or the digging in itself, but to make more challenging the game.
As an example:
instead of sending a dig team out and 15 seconds later, after the box animation finishes, having a sparkling new dinosaur, you would instead get dinosaur DNA which in itself is not enough to obtain the new species.
To unlock the new dinosaur for use in your park you would have to find the DNA of that species ebough time to complete it's genome sequence, this way the game would feel more satisfactory when finding dinosaurs while also being more faithful to the original Jurassic Park Operation Genesis, a Game that Mesozoica likes to call its inspiration and often claimed to be a spiritual successor of :)
