### ISSUE TITLE
Too much money

### ISSUE THREAD

**Issue by unicorncatbug** [mwdossantos/squadroninteractive#430]
We start out with so much money, it is so easy to build things that would be fairly expensive, plz either make things more expensive like they should be or cut down our beginning salary, and also the dinosaurs r pretty cheap, we r bringing back prehistoric creatures that have been extinct for millions of years

**Comment by Huntertje2000** [comment]
Dude its 250 bucks for a plant pot... Making less money ok thats fine but don't make it more expensive.

**Comment by lukefox01** [comment]
I also think a popularity system like the one in JPOG would work well. It doesn't make much sense to have people pouring into the park when nothing is even there. Once you have the first dino, people should start coming but only a little at first. Then as you expand, more and more people come. As of the moment money is not an issue in game as you get so much.
