### ISSUE TITLE
visitor mosh pit, dinosaur bug and waterpond disappeared

### ISSUE THREAD

**Issue by turkayturk** [mwdossantos/squadroninteractive#433]
![20180103204142_1](https://user-images.githubusercontent.com/35076437/34534142-202b4be8-f0ce-11e7-9bb0-036921bed8b1.jpg)
those visitor want to sit a table, and other bugs 
- sometimes dinosaurs hang out with waterpond and foods,
- waterpond which in baryonyx paddock has disappeared

**Comment by locomain** [comment]
Hi,

First of all thanks for your bug report.
Can you tell me more about the visitor bug?
When did it happen and how can i reproduce it?

**Comment by turkayturk** [comment]
visitor bug happens when visitors want to sit a picnic table

**Comment by locomain** [comment]
can you be more precise?
Is it after you loaded your park or does this happen after a long time playing?
Did you add or remove something before this happend?
is it still happening in the latest update?

**Comment by nqwebasaurus** [comment]
Even if i did not do the original report:
They do it even in the latest update after some time playing and it happens with every tipe of chair or bench.
If they start doing that, reloading the game doesn't solve the problem, to make them stop you have to either move the bench/chair or remove it altogether
