### ISSUE TITLE
Dinosaur drinking / jittering and freezing problem

### ISSUE THREAD

**Issue by Paliath** [mwdossantos/squadroninteractive#459]
http://steamcommunity.com/sharedfiles/filedetails/?id=1259319775 you might not be able to see it in a screenshot but ive noticed that there seems to be certain sections of a water source/ drinking area that dinosaurs go to for water. But when their is more then 1 dino in a selected spot, they seems to block themselves from being able to drink. causing them to jitter intensly or get stuck. im noticed this by having 7 velociraptors in a padok and them trying to drink all at once. It took controlling them and moving them manually an hour to get them to all drink serperatly and find the sweet spot. http://steamcommunity.com/sharedfiles/filedetails/?id=1259322453 heres a better repersentation, all of them gathered in the sweet spot and none are able to drink, instead are jittering and freezing. Same thing is also happening to my pen of 7 styracosaurs. The drinking ponds are also enlarged so they should all be able to drink at once if it wasnt for the sweet spot thing

**Comment by S1rMuff1nz** [comment]
I have this exact issue with my velociraptors
