### ISSUE TITLE
Dino resized and with wrong skin after saving, exiting and entering game again

### ISSUE THREAD

**Issue by keawstudio** [mwdossantos/squadroninteractive#46]
Issue:
Smaller dinos and wrong skin after loading a saved park

What happened:
Yesterday I played and created three raptors. Unlocked all skins and use the first and the ice one.
Dinos grew very quickly. Saved the game and exited it.
Today I loaded the same park again, and the raptors are now the same size, very small, and with the same skin, and looks like it isn't one of skins I choose before.
Also the dino is locked up again in the Hatchery screen.

Video:
https://drive.google.com/open?id=11S5KZGkpQ9vyTAfSEJtsn02Aa7JtfJOv

[system_specs.txt](https://github.com/mwdossantos/squadron/files/1527728/system_specs.txt)

**Comment by NathanaelHembree** [comment]
+1 but my dinos came out at full size and with the skins, I chose before I saved and now they are small(babies) and refuse to move and I got trapped in my Pachyrhinos's body, to which I had to force close the game.

**Comment by keawstudio** [comment]
Can also be seen in the video from issue #86 at 12:40
