### ISSUE TITLE
FPS Drops

### ISSUE THREAD

**Issue by Nightcharmer1** [mwdossantos/squadroninteractive#464]
As the title says, I get 8 fps now that I have my park established. But if I destroy all the fences, It goes back to 60fps
Specs:
GPU: NVIDIA GTX Geforce 970
CPU: I5-3570k
Motherboard: Model DH67BL
RAM: 12GBs
422.7GB of free storage

Do I really have to upgrade my GPU AGAIN, (just bought this 970 about 3-4 months ago) to be able to play this game?

**Comment by Larvtrams** [comment]
Any chance you could provide a screenshot of your park?
