### ISSUE TITLE
Add dinosaur to main menu GUI

### ISSUE THREAD

**Issue by mwdossantos** [mwdossantos/squadroninteractive#48]
This would make the Main Menu GUI a lot more interactive and nice to look at! :)

**Comment by ElysePanici** [comment]
+1

**Comment by mwdossantos** [comment]
How do you mean exactly?

**Comment by ElysePanici** [comment]
Like how JPOG does it. Underneath the main category of 'Dinosaurs' you have 'DNA'/Digsites, Fences, hatchery, food items for the dinosaurs.
