### ISSUE TITLE
Modular Sets (suggestion)

### ISSUE THREAD

**Issue by JacobSawyer** [mwdossantos/squadroninteractive#56]
I find that grouping together every item you place down so you cant edit or delete a singular part is very bothersome. It should only group up the building parts and there should be a pop up at the end that says "would you like to group these together." For example I was just making decorations and what not and then went on to testing out the mod mechanic and then when I wanted to delete the building parts it will only let me delete the entire thing. 
![image](https://user-images.githubusercontent.com/34224008/33580816-3346f078-d914-11e7-90a3-9cab83aaecc1.png)

**Comment by ForeverLona** [comment]
+1 

I find it very counter intuitive in its current state

**Comment by JacobSawyer** [comment]
I figured it out, you press the wrench and it lets you edit the whole thing, still the option to not make them into a set would be great.
