### ISSUE TITLE
To many visitors Spawn to fast

### ISSUE THREAD

**Issue by JacobSawyer** [mwdossantos/squadroninteractive#59]
There will be a hundred in just a little bit of path
![image](https://user-images.githubusercontent.com/34224008/33581422-66247ce8-d916-11e7-95ef-08a785bede2a.png)

**Comment by keawstudio** [comment]
Same problem I'm having, they are grouped and walk all together.

**Comment by keawstudio** [comment]
Can be seen in the gameplay video from issue #86 at 15:05
