### ISSUE TITLE
Mouse on Screen while controlling dinosaur

### ISSUE THREAD

**Issue by JacobSawyer** [mwdossantos/squadroninteractive#60]
Im not sure if its a bug or not but it looks clunky and makes controlling a dinosaur feel odd.

[2017-12-04 18-18-21.zip](https://github.com/mwdossantos/squadron/files/1529247/2017-12-04.18-18-21.zip)

**Comment by mwdossantos** [comment]
I don't see a mouse cursor?

**Comment by JacobSawyer** [comment]
Yeah it was showing up in my game but not on the screenshot, I have no idea why that would be the case.

**Comment by JacobSawyer** [comment]
I went back to see if I could try again but my game had crashed.

**Comment by mwdossantos** [comment]
Let me know.

**Comment by JacobSawyer** [comment]
It happened once again but still does not show up on screenshots which baffles me, maybe i can get a recording of it.

**Comment by JacobSawyer** [comment]
I uploaded a link to the video of mouse on screen

**Comment by mwdossantos** [comment]
We will take a look at this!

**Comment by RileyFoster** [comment]
I had this happen to me when I alt+tabbed out of the game in fullscreen controlling a dinosaur. I reopened the game from the taskbar and the cursor was on the screen.
