### ISSUE TITLE
99% Hatchery then stop

### ISSUE THREAD

**Issue by DuckTapeMan** [mwdossantos/squadroninteractive#7]
I've encountered twice that when I make the Mamenchisaurus, it freezes at 99%.
![mesozoica 12_3_2017 7_06_07 pm](https://user-images.githubusercontent.com/34223342/33535210-ca890136-d871-11e7-94e6-4a99da8524dc.png)

**Comment by ElysePanici** [comment]
I second this. I have not been able to create a Mamenchisaurus.

**Comment by DuckTapeMan** [comment]
I watched it this time. Tried to make 3, as soon as it got to 99% it took one away then stayed at 99%.

**Comment by JacobSawyer** [comment]
Exact same thing happened to me

**Comment by keawstudio** [comment]
Same here, and with the mamenchi.
