### ISSUE TITLE
Pathway Placement Toolbar Issues

### ISSUE THREAD

**Issue by DuckTapeMan** [mwdossantos/squadroninteractive#70]
Just started up the game, placed down a few pathways, deleted a few, wouldn't let me exit out of the toolbar. Some of the paths I couldn't click on until I put other paths on top of them. Also just got back onto the same save, and it went fine till I got finished decorating, then the pathway toolbar had nothing on it.
![mesozoica 12_4_2017 9_00_12 pm](https://user-images.githubusercontent.com/34223342/33588089-9fed3df0-d936-11e7-9451-08c8e319f96f.png)

**Comment by JacobSawyer** [comment]
you need to go click that back arrow in the top center of the menu.

**Comment by DuckTapeMan** [comment]
When I couldn't exit, I did click it multiple times and tried different ways of trying to get out of it.

**Comment by ForeverLona** [comment]
Could this be related to issue #35 ?

**Comment by vkDreamInCode** [comment]
try to make a video of what happend before the bug appeared
