### ISSUE TITLE
Suggestion — Modular Set menu tweak

### ISSUE THREAD

**Issue by RileyFoster** [mwdossantos/squadroninteractive#74]
To make the Modular Set menu more intuitive, I believe that the Modular Set Settings should open by default when opening the menu itself. More often than not, the user will be selecting something from the Settings when using that menu, so it would remove an extra step for the user. 

![582ff6966ab2b3513a6cbc9c7a9a585e](https://user-images.githubusercontent.com/34225763/33588594-b58e7d9e-d941-11e7-9db5-c36b366dc8b6.gif)

**Comment by ElysePanici** [comment]
+1
