### ISSUE TITLE
Game crashes while trying to save 

### ISSUE THREAD

**Issue by casmorrison** [mwdossantos/squadroninteractive#87]
1) was trying to save the game - game crashed
2) would expect it to save normally 
3)I was just possessing/ controlling a parasaurolohus and left controlling it and tried to save the game within a few Seconds 
The it crashed
4) to replicate - control a dino, the leave it and try to save the game asap

5) error message and game crashes - game killer

6) system will have to look it up

**Comment by vordik660** [comment]
I have had the same twice even with no dinos in the park, all i had was foliage and the rex statue and terraformed hills. I have the crash reports saved on my desktop but github doesnt seem to support the file type... Alex Goldsmith
